### PR TITLE
Redesign Front End and Responsive ✅

### PR DESCRIPTION
**Pull request by gnwncpta**
Big changes on home page based on design guideline, Thanks. For everyone who want to contribute on front end you can do the rest, it's Navigation Bar.

### CODE REVIEW

**Comment by unnikrishnan2002** [comment]
Hey @gnwncpta great work but there are some merge conflicts in the PR can you resolve those ?

**Comment by gnwncpta** [comment]
@unnikrishnan2002 how come it's conflicted ?

**Comment by unnikrishnan2002** [comment]
Maybe because I merged a PR so your branch is behind master. I guess it will be resolved if you pull the changes and push it in this pr

**Comment by gnwncpta** [comment]
Let me try to fix this problem

**Pull request closed without merging**
